---

- hosts: [localhost]
  tasks:
  # Install Java,SSH,GIT,Gradle,Tomcat,Jenkins,docker,dockercompose.
     #Install Java
    - name: Install Java.
      yum:
        name: java-1.8.0-openjdk*
        state: present
     # SSH key setup with empty passphrase
    - name: ssh-key setup
      shell: yes | ssh-keygen -N '' -f /root/.ssh/id_rsa
    - name: start ssh-agent
      shell: eval "$(ssh-agent -s)"
    - name: run sshagent
      shell: ssh-agent bash
    - name: add ssh-key to agent
      shell: ssh-add /root/.ssh/id_rsa
    - name: copying ssh-key to a file
      fetch: src=/root/.ssh/id_rsa.pub dest=/root/git/sshkey.txt flat=yes
     # Install pre-requisites for GIT
    - name: Install get-text
      yum:
       name: gettext-devel
       state: present
    - name: Install expat
      yum:
       name: expat-devel
       state: present
    - name: Install curl
      yum:
       name: curl-devel
       state: present
    - name: Install zlib
      yum:
       name: zlib-devel
       state: present
    - name: Install openssl
      yum:
       name: openssl-devel
       state: present
     # Install GIT
    - name : Install GIT
      yum:
       name: git
       state: latest
     # Install gradle
    - name: creates required directory
      file:
       path: /opt/gradletemp
       state: directory
       mode: 777
       recurse: yes
    - name: creates required directory
      file:
        path: /opt/gradle
        state: directory
        mode: 777
        recurse: yes
    - name: download gradle
      get_url:
        url: https://services.gradle.org/distributions/gradle-4.0.2-bin.zip
        dest: /opt/gradletemp
    - name: unzip downloaded file
      unarchive:
        src: /opt/gradletemp/gradle-4.0.2-bin.zip
        dest: /opt/gradle
    - name: creates softlink for gradle executable
      shell: ln -s /opt/gradle/gradle-4.0.2/bin/gradle /usr/local/bin/gradle creates=/usr/local/bin/gradle
     # Install tomcat and configure users for Jenkins
    - name: creates required directory
      file:
        path: /opt/tomcat
        state: directory
        mode: 777
        recurse: yes
    - name: creates required directory
      file:
        path: /usr/local/tomcat
        state: directory
        mode: 777
        recurse: yes
    - name: download tomcat
      get_url:
        url: http://redrockdigimark.com/apachemirror/tomcat/tomcat-9/v9.0.1/bin/apache-tomcat-9.0.1.tar.gz
        dest: /opt/tomcat
    - name: unzip downloaded file
      unarchive:
        src: /opt/tomcat/apache-tomcat-9.0.1.tar.gz
        dest: /opt/tomcat
    - name: configure tomcat_users.xml - manager app for Jenkins
      blockinfile:
        path: /opt/tomcat/apache-tomcat-9.0.1/conf/tomcat-users.xml
        block: |
          <role rolename="manager-gui"/>
          <role rolename="manager-script"/>
          <role rolename="manager-jmx"/>
          <role rolename="manager-status"/>
          <role rolename="admin-gui"/>
          <role rolename="admin-script"/>
          <user username="redhatmaster" password="devops1" roles="manager-gui,manager-script,manager-jmx,manager-status,admin-gui,admin-script"/>
    - name: rum tomcat startup script
      shell: sh /opt/tomcat/apache-tomcat-9.0.1/bin/startup.sh
      msg: "Congrates Tomcat has been setup .. verify at localhost:8080"
    #Install Jenkins
    - name:
      get_url:
        #url: https://updates.jenkins-ci.org/download/war/2.7.3/jenkins.war
        url: https://updates.jenkins-ci.org/download/war/
        dest: /opt/
    # Install docker and dockercompose
    - name: configure yum-epel for docker
      shell: yum-config-manager --enable rhel-7-server-extras-rpms
    - name: configure repo
      yum_repository:
        name: docker
        description: docker repo
        baseurl: https://packages.docker.com/1.13/yum/repo/main/centos/7
        gpgcheck: no
    - name: run yum update
      shell: yum update -y
    - name: Install docker 1.13 # note docker dockercompose requires docker 1.13 and +
      yum:
        name: docker-engine-1.13*
        state: present
    - name: Install dockercompose
      shell: curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    - name:
      file:
        path: /usr/local/bin/docker-compose
        mode: 0655
...
